version: "3.9"
services: 
  devfinder-db:
    image: postgres
    restart: always
    container_name: devfinder-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dbpass
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes: 
  postgres:
  